language: php
env:
  global:
  - CLOUD_NAME=kylephp
  - GITHUB_TOKEN=89c98a94a2b870cfc4fb1659163bb26bb3159ece
  - ORGANIZATION=KYLE-LAB
  - REPO=com_dummy
php:
- 5.5
script:
- php .travis/misseddebugcodechecker.php component/ libraries/dummy/ modules/ plugins/
- php .travis/phppec.php component/ libraries/dummy/ modules/ plugins/
notifications:
  slack:
    rooms:
      secure: NC4yRoZNf1U8ByRICn0sSQR7BM+Y2SZtCm7bTRjWV+nNFOHs1AxPRIx9BSmMaO1gzqvVRLRRKH9IsBiIC915XabGszicicg1r6Y2Sbj+mu8BRRPHSDeQ7huPltMZdDFSB0jicBrVAxJBd3XvuceCjIj4qQVW+FbxZp1Dypj4KVERcPd/JZV8sV1l8rMtHF/aey8HfeaERNsU8Rfb42FrlARE+w+D9gdwjs9EQTL2lRk1O8JbfZ8PU9oPZIHtLineXbmZ00KVjE7hyb5F3ycm0GMqYgRm7WDfbJKOKd3ZRJGiB93+yM5Sa5jCUvm9Qf9iooFupHiHPSYa0zIqmTFl9OYSZ0VeidgmtggnOdvHDQPCd9TBf67jhn1VVHc1CbJtUGBCz2LohayRvNck2/xKtDSkJj/QfLmN9Dkq8uvD4TW/cYp8IBqtltvpbQ5meZj+ySLYFE2dMnQn642v1fap+GatK0q0qBNxFfKyIpRFtiAfz71rgvxvlLklM5sa+sr9yQ/+eQ8Mnh9lIMmSQOFIintLKAeA4L7fYv/kVeH/PqcDmjwv5fioDE+BwFNUixA+NBNgpT+duN7mehsuwgQ9U1x39CmwmnJ2zc/mPckIe+p086yWgQ6Z9by0RTcnZpOqWmMpGvKV2sRjsnDRVyTyX0RS5kb5JNhkMRbhgrmi2Q8=
