language: php
env:
  global:
  - CLOUD_NAME=kylephp
  - GITHUB_TOKEN=89c98a94a2b870cfc4fb1659163bb26bb3159ece
  - ORGANIZATION=KYLE-LAB
  - REPO=com_dummy
php:
- 5.5
script:
- php .travis/misseddebugcodechecker.php component/ libraries/dummy/ modules/ plugins/
- php .travis/phppec.php component/ libraries/dummy/ modules/ plugins/
notifications:
  slack:
    secure: HgNAr12XYxa8EoGBmRI9FRU/0VLAYjhLYSrcOhrNljRhEMJYzGnHWJXWxV3urrkjlJ5/+B8JAlSYp1wTz08gdTWFmX48O/LCV1bhID/U6SHYox23weNmNQrVvEpahVa7tHqW5l3fNQn3tsqhcmlGCHXmeKGbtYqPbydOV0ACeczjrKwNCSPlJdgZxCaRgH2hda4SIwmNrU/cYX3L/Q1W430p9K5X7RJQlt4p7Eoztw9sGNB2hdhuPDoUaPkxUU2q4GY7sMQDkpddmsfruWb3R6QiRSVBZ3Bidlx0aNAp8c7skMCc1wQu4tqqrpzKGGhP44ZRL5UiKZWa6ipvVvl9V6uWVmhtEuGAm8fmB6LRXq/cOfcz88NqP+4Pk4ZUle0R4n8w4TKMfTTKnh6VFR44jgTNniJ8xEtaUqe8zGV6PsO6IpLA9cwLRlda8U+AD90GWkD0lasYlGYu8/ZQE/MK0lC/ig1marXc0PJquxzTNYbokPEzh0GWDsG//JniQYZtxUNRT1sSBLADfpUhWJFSZWtHPGZ6whUqjJib3m3ue1D+iuAtNHNHGvJz6Z1nF+uNwvJUuj9NJwdczSNlfMFBDsAWFHhcCSF3F4Epx3MPi0uAjfMEUusmiivrwyXYVsDQ99+rVEFdZ6RSw9zVqEneEg+UeauXbkayA2Y7/kXNy6I=
