language: php
env:
  global:
  - CLOUD_NAME=kylephp
  - GITHUB_TOKEN=89c98a94a2b870cfc4fb1659163bb26bb3159ece
  - ORGANIZATION=KYLE-LAB
  - REPO=com_dummy
php:
- 5.5
script:
- php .travis/misseddebugcodechecker.php component/ libraries/dummy/ modules/ plugins/
- php .travis/phppec.php component/ libraries/dummy/ modules/ plugins/
notifications:
  slack:
    rooms:
      secure: vlYMDeJzYEe8MZlc1VUkX42fTwSrlEFeeEdoj+jzrati0HnhauiV5CVOg7zkpliSrOBt5RvfQiVe9eYcZ/QBLutz7Iwo68mVKaEQ9LIlpe2chdSfu5ZmT0Kc3RxC/g5WDoT1HyL4j9NWAr93UEm+g3b1eEn4fzxJOggu5w/13zYXRuYx+IJTsM6NZt2JJAOwApV9eZc76Rh6UfjCPaHyuIoyPrPNhHied4JieRjg15+YR5lC2dogSyhySRExmX9LNhb1Prr966TS3Sf6kbAlCZxkiQVRdJpTEYp8D2ogbq2KSYwH6LhzOcL9mdp2K8t07wleXFU0lCTSiXamtDdnAnvlf+VP/bBJz66lr5A7MuOMaGwwLCSzwV3YiCvxUSrC4UUOL1/LuXNdbd8WuSoydsdvQgL/uCH7Do7j+axQq4bK18z3YLMQT5RGmGS0NF2aLCZ4RXtuV7cvTLo1zmHL7byl6ow3yNsPWHUBo1ywTr716vhiPuhU6mlUKd/6+gkmEteKgNnBrm+I9XGIKXMJfefCSEju+2knP9Wy2BIvCCzqWZNfUuhW7LwCulHY/6IvL+d9KYHAAwGmjM1a5XFSbv70EplHPWU7GKQdsvoJwdx6MVlJNdKYqwLrUEd6w2Nh3Y9/dymVuntuNzKEUEub1B1cAuo9Fhg+gmDnWe4VnrA=
